## Promise

> 자바스크립트에서 제공하는 비동기를 간편하게 처리할수 있도록 도와주는 오브젝트
>
> 정해진 장시간의 기능을 수행하고 나서 정상적으로 기능이 수행이 되어졌다면 성공 메시지와 처리된 값을 전달
>
> 예상치 못한 문제 발생하면 에러 전달

promise is a JavaScript object for asynchronous operation. 

프로미스는 자바스크립트 안에 내장된 비동기적인 것을 수행할 때 콜백 함수 대신 쓰이는 유용한 오브젝트

state: pending(오퍼레이션이 수행중일 때) -> fulfilled(오퍼레이션이 성공적으로 끝) or rejected (파일을 찾을 수 없거나 네트워크 문제가 생기면)

Producer(원하는 기능을 수행해서 해당하는 데이터를 만들어내는 promise object) vs Consumer(원하는 데이터를 소비하는)

```js
// 1. Producer

// 프로미스는 클래스이기 때문에 new 키워드로 오브젝트를 생성할 수 있음
// 프로미스의 생성자를 보면 executor 라는 콜백함수를 전달해줘야하는데, 이 콜백 함수에는 또 다른 두가지 콜백 함수를 받음
// 기능을 정상적으로 수행해서 마지막에 최종 data를 전달하는 resolve 콜백 함수
// 기능을 수행하다가 중간에 문제가 생기면 호출하게 될 reject 콜백 함수

// when new Promise is created, the executor runs automatically. 
// 불필요한 네트워크 연결 등을 수행할 수 있기 때문에 유의해야 함.
const promise = new Promise((resolve, reject) => {
    // doing some heavy work (network, read files...). 시간이 좀 걸리는 무거운 동작은 프로미스를 만들어서 비동기적으로 처리
    console.log('doing something...');
    setTimeout(() => {
        resolve('ellie');
        // reject(new Error('no network'));
    }, 2000);
});

// 2. Consumers: then, catch, finally 를 이용해서 값을 받아올 수 있음
// then: 프로미스 기능이 원할히 이루어졌을 때
// catch: 오류 발생했을 때 에러메시지
// finally: 기능이 성공하던 실패하던 수행
promise
    .then((value) => { // value라는 파라미터는 프로미스가 정상적으로 잘 수행이 되어서 마지막 resolve 콜백 함수에서 전달된 값
        console.log(value); // ellie 출력 (2초 후)
    })
    .catch(error => {
        console.log(error); // 프로미스에서 reject를 리턴했을 때 에러를 출력하지 않고 catch 블록 실행
    })
    .finally(() => { // 성공하든 실패하던 무조건 마지막에 호출되는 구문
        console.log('finally'); // finally
})

// 3. Promise chaining : 프로미스에 then을 호출하면 똑같은 프로미스를 호출하기 때문에 그 호출된 프로미스에 다시 then이나 catch 호출
const fetchNumber = new Promise((resolve, reject) => {
    setTimeout(() => resolve(1),1000);
});

fetchNumber
    .then(num => num * 2) // 2
    .then(num => num * 3) // 6
    .then(num => { // then 은 값을 전달해도 되고 또다른 비동기인 프로미스를 전달해도 됨
        return new Promise((resolve, reject) => {
            setTimeout(() => resolve(num-1),1000);
        })
    })
    .then(num => console.log(num)); // 5

// 4. Error Handling
const getHen = () =>
    new Promise((resolve, reject) => {
        setTimeout(() => resolve('🐓'), 1000);
    });
const getEgg = hen =>
    new Promise((resolve, reject) => {
        setTimeout(() => reject(new Error(`${hen} => 🥚`), 1000));
    });
const cook = egg =>
    new Promise((resolve, reject) => {
        setTimeout(() => resolve(`${egg} => 🍳`), 1000);
    });

// getHen()
//	.then(hen => getEgg(hen)) //  .then(getEgg) : 콜백함수를 정의할때 받아오는 밸류를 다른 함수로 바로 하나를 호출하는 경우 생갹가능
//	.then(egg => cook(egg)) 	//	.then(cook) 
//  .then(meal => console.log(meal)); // then(console.log) // 🐓 => 🥚 => 🍳

달걀을 받아오는 부분에서 네트워크 문제가 생겨서 실패가 되면?
// const getEgg = hen =>
//    new Promise((resolve, reject) => {
//        setTimeout(() => reject(new Error(`error! ${hen} => 🥚`), 1000));
//    });

getHen() //
.then(getEgg)
.catch(eroor => {
    return '🍞';
})
.then(cook)
.then(console.log)
.catch(console.log); // 🍞 => 🍳
```



콜백 지옥 프로미스로 해결하기

```js
console.clear();
class UserStorage {
    loginUser(id, password) {
      return new Promise((resolve, reject)=>{
      	setTimeout(() => {
        	if (
            (id === 'ellie' && password === 'dream') ||
            (id === 'coder' && password === 'academy')
          ) {
            resolve(id);
        	} else {
            reject(new Error('not found'));
        	}
        }, 2000);
    	});
  
    getRoles(user) {
			return new Promise((resolve, reject)=>{
    	  setTimeout(() => {
        	if (user === 'ellie') {
            resolve({ name: 'ellie', role: 'admin' });
        	} else {
            reject(new Error('no access'));
        	}
        }, 1000);
      });
		}

const userStorage = new UserStorage();
const id = prompt('enter ur id');
const password = prompt('enter ur pw');
userStorage.loginUser(
    id,
    password,
    user => {
        userStorage.getRoles(
            user,
            userWithRole=>{
                alert(`hello ${userWithRole.name}, you have a ${userWithRole.role}`);
            },
            error => {console.log(error);});
    },
    error => {console.log(error);}
);
```

